# Site settings
title: AnonymMJ
name: 梦境
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "种一颗树最好的机会是在十年前，第二就是现在。"  
baseurl: ""
url: "http://www.AnonymMJ.com"  

# About/contact
owner: 
  name: " AnonymMJ"
  email: AnonymMJ@gmail.com
  bio: "写就是写的报酬"

# Data
gavatar: http://oobn39nrf.bkt.clouddn.com/MJ.png
favicon: http://oobn39nrf.bkt.clouddn.com/small_MJ.png

github_username: AnonymMJ
facebook_username: AnonymMJ丶
weibo_username: 丶醉丶梦丶境丶 
zhihu_username: 梦境丶

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AnonymMJ"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  disqus :
      short_name : AnonymMJ

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
